packages:
  - apps/*

catalogMode: prefer

catalog:
  typescript: ^6
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vite-plus: ^0.1.24
  shiki: ^4.2.0
  html-to-image: ^1.11.13
  lit: ^3.3.3
overrides:
  vite: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
