import type { ThemeRegistration } from "shiki/core";

const sourceShotLightVariables = {
  "--text": "#6b6375",
  "--text-h": "#08060d",
  "--bg": "#e07a5f",
  "--bg-glow-warm": "#f2b06f",
  "--bg-glow-rose": "#cf536d",
  "--bg-glow-violet": "#6f3e98",
  "--bg-glow-light": "#f3dfc7",
  "--bg-noise-opacity": "1",
  "--border": "#e5e4e7",
  "--code-bg": "#f4f3ec",
  "--accent": "#aa3bff",
  "--accent-bg": "rgba(170, 59, 255, 0.1)",
  "--accent-border": "rgba(170, 59, 255, 0.5)",
  "--social-bg": "rgba(244, 243, 236, 0.5)",
  "--shadow": "rgba(0, 0, 0, 0.1) 0 10px 15px -3px, rgba(0, 0, 0, 0.05) 0 4px 6px -2px",
  "--brand-title": "#000000",
  "--glass": "#ececf0",
  "--glass-light": "#ffffff",
  "--glass-dark": "#000000",
  "--glass-reflex-dark": "1",
  "--glass-reflex-light": "1",
  "--glass-saturation": "150%",
  "--code-container-border": "#ffffff",
  "--code-container-bg": "#fbf4ee",
  "--code-container-fill-start": "56%",
  "--code-container-fill-mid": "22%",
  "--code-container-shine": "46%",
  "--code-container-top-reflex": "46%",
  "--code-container-border-start": "96%",
  "--code-container-border-end": "100%",
  "--code-container-overlay-opacity": "0.82",
} as const;

type ThemeCssVariableName = keyof typeof sourceShotLightVariables;
export type ThemeCssVariables = Readonly<Record<ThemeCssVariableName, string>>;

const sourceShotDarkVariables = {
  "--text": "#a9b1bd",
  "--text-h": "#f6f2eb",
  "--bg": "#111116",
  "--bg-glow-warm": "#a44e39",
  "--bg-glow-rose": "#65324c",
  "--bg-glow-violet": "#302756",
  "--bg-glow-light": "#1e4c52",
  "--bg-noise-opacity": "0.72",
  "--border": "#2b2d35",
  "--code-bg": "#171820",
  "--accent": "#77dac8",
  "--accent-bg": "rgba(119, 218, 200, 0.14)",
  "--accent-border": "rgba(119, 218, 200, 0.48)",
  "--social-bg": "rgba(30, 33, 42, 0.52)",
  "--shadow": "rgba(0, 0, 0, 0.46) 0 16px 34px -8px, rgba(0, 0, 0, 0.32) 0 6px 12px -4px",
  "--brand-title": "#fff6ec",
  "--glass": "#4a5360",
  "--glass-light": "#ffffff",
  "--glass-dark": "#000000",
  "--glass-reflex-dark": "2.1",
  "--glass-reflex-light": "0.36",
  "--glass-saturation": "176%",
  "--code-container-border": "#2e3340",
  "--code-container-bg": "#11151e",
  "--code-container-fill-start": "48%",
  "--code-container-fill-mid": "18%",
  "--code-container-shine": "22%",
  "--code-container-top-reflex": "28%",
  "--code-container-border-start": "54%",
  "--code-container-border-end": "58%",
  "--code-container-overlay-opacity": "0.42",
} as const satisfies ThemeCssVariables;

const sourceShotMonoVariables = {
  "--text": "#4f554f",
  "--text-h": "#222323",
  "--bg": "#f0f6f0",
  "--bg-glow-warm": "#f8fff8",
  "--bg-glow-rose": "#dbe2db",
  "--bg-glow-violet": "#626862",
  "--bg-glow-light": "#ffffff",
  "--bg-noise-opacity": "0.44",
  "--border": "#cdd6cd",
  "--code-bg": "#eef4ee",
  "--accent": "#222323",
  "--accent-bg": "rgba(34, 35, 35, 0.08)",
  "--accent-border": "rgba(34, 35, 35, 0.46)",
  "--social-bg": "rgba(240, 246, 240, 0.58)",
  "--shadow": "rgba(34, 35, 35, 0.16) 0 14px 28px -8px, rgba(34, 35, 35, 0.08) 0 6px 12px -4px",
  "--brand-title": "#222323",
  "--glass": "#f0f6f0",
  "--glass-light": "#ffffff",
  "--glass-dark": "#222323",
  "--glass-reflex-dark": "1.18",
  "--glass-reflex-light": "0.82",
  "--glass-saturation": "0%",
  "--code-container-border": "#f0f6f0",
  "--code-container-bg": "#edf3ed",
  "--code-container-fill-start": "50%",
  "--code-container-fill-mid": "18%",
  "--code-container-shine": "34%",
  "--code-container-top-reflex": "40%",
  "--code-container-border-start": "84%",
  "--code-container-border-end": "70%",
  "--code-container-overlay-opacity": "0.5",
} as const satisfies ThemeCssVariables;

const sourceShotMonoDarkVariables = {
  "--text": "#d7ded7",
  "--text-h": "#f0f6f0",
  "--bg": "#222323",
  "--bg-glow-warm": "#f0f6f0",
  "--bg-glow-rose": "#3d403d",
  "--bg-glow-violet": "#111212",
  "--bg-glow-light": "#697069",
  "--bg-noise-opacity": "0.36",
  "--border": "#444944",
  "--code-bg": "#1f2020",
  "--accent": "#f0f6f0",
  "--accent-bg": "rgba(240, 246, 240, 0.1)",
  "--accent-border": "rgba(240, 246, 240, 0.48)",
  "--social-bg": "rgba(34, 35, 35, 0.58)",
  "--shadow": "rgba(0, 0, 0, 0.52) 0 16px 34px -8px, rgba(0, 0, 0, 0.34) 0 6px 12px -4px",
  "--brand-title": "#f7fff7",
  "--glass": "#3d403d",
  "--glass-light": "#f0f6f0",
  "--glass-dark": "#000000",
  "--glass-reflex-dark": "1.9",
  "--glass-reflex-light": "0.34",
  "--glass-saturation": "0%",
  "--code-container-border": "#3d403d",
  "--code-container-bg": "#222323",
  "--code-container-fill-start": "42%",
  "--code-container-fill-mid": "16%",
  "--code-container-shine": "18%",
  "--code-container-top-reflex": "28%",
  "--code-container-border-start": "58%",
  "--code-container-border-end": "44%",
  "--code-container-overlay-opacity": "0.48",
} as const satisfies ThemeCssVariables;

const sourceShotAquaLightVariables = {
  "--text": "#224DA2",
  "--text-h": "#191C4F",
  "--bg": "#58B9DE",
  "--bg-glow-warm": "#A9E1F2",
  "--bg-glow-rose": "#BFE9F5",
  "--bg-glow-violet": "#3B7FC2",
  "--bg-glow-light": "#D2EFF8",
  "--bg-noise-opacity": "0.58",
  "--border": "#A9E1F2",
  "--code-bg": "#D2EFF8",
  "--accent": "#0B1376",
  "--accent-bg": "rgba(11, 19, 118, 0.1)",
  "--accent-border": "rgba(11, 19, 118, 0.42)",
  "--social-bg": "rgba(210, 239, 248, 0.58)",
  "--shadow": "rgba(11, 19, 118, 0.18) 0 16px 34px -8px, rgba(34, 77, 162, 0.12) 0 6px 12px -4px",
  "--brand-title": "#191C4F",
  "--glass": "#BFE9F5",
  "--glass-light": "#D2EFF8",
  "--glass-dark": "#0B1376",
  "--glass-reflex-dark": "1.24",
  "--glass-reflex-light": "0.92",
  "--glass-saturation": "168%",
  "--code-container-border": "#D2EFF8",
  "--code-container-bg": "#D2EFF8",
  "--code-container-fill-start": "54%",
  "--code-container-fill-mid": "24%",
  "--code-container-shine": "42%",
  "--code-container-top-reflex": "44%",
  "--code-container-border-start": "92%",
  "--code-container-border-end": "82%",
  "--code-container-overlay-opacity": "0.58",
} as const satisfies ThemeCssVariables;

const sourceShotAquaDarkVariables = {
  "--text": "#78CAE7",
  "--text-h": "#D1ECF4",
  "--bg": "#020440",
  "--bg-glow-warm": "#070F72",
  "--bg-glow-rose": "#1D49A0",
  "--bg-glow-violet": "#020440",
  "--bg-glow-light": "#1D49A0",
  "--bg-noise-opacity": "0.44",
  "--border": "#070F72",
  "--code-bg": "#070F72",
  "--accent": "#A5DEF0",
  "--accent-bg": "rgba(165, 222, 240, 0.14)",
  "--accent-border": "rgba(165, 222, 240, 0.5)",
  "--social-bg": "rgba(7, 15, 114, 0.6)",
  "--shadow": "rgba(0, 0, 0, 0.64) 0 20px 48px -10px, rgba(2, 4, 64, 0.5) 0 8px 18px -6px",
  "--brand-title": "#D1ECF4",
  "--glass": "#1D49A0",
  "--glass-light": "#D1ECF4",
  "--glass-dark": "#020440",
  "--glass-reflex-dark": "2.45",
  "--glass-reflex-light": "0.32",
  "--glass-saturation": "210%",
  "--code-container-border": "#1D49A0",
  "--code-container-bg": "#070F72",
  "--code-container-fill-start": "42%",
  "--code-container-fill-mid": "16%",
  "--code-container-shine": "16%",
  "--code-container-top-reflex": "24%",
  "--code-container-border-start": "50%",
  "--code-container-border-end": "42%",
  "--code-container-overlay-opacity": "0.44",
} as const satisfies ThemeCssVariables;

const sourceShotLotusLightVariables = {
  "--text": "#375A3C",
  "--text-h": "#233325",
  "--bg": "#A3D1A5",
  "--bg-glow-warm": "#BADDBA",
  "--bg-glow-rose": "#D1EACE",
  "--bg-glow-violet": "#6FA977",
  "--bg-glow-light": "#E5F5E1",
  "--bg-noise-opacity": "0.52",
  "--border": "#BADDBA",
  "--code-bg": "#E5F5E1",
  "--accent": "#183521",
  "--accent-bg": "rgba(24, 53, 33, 0.1)",
  "--accent-border": "rgba(24, 53, 33, 0.42)",
  "--social-bg": "rgba(229, 245, 225, 0.6)",
  "--shadow": "rgba(24, 53, 33, 0.18) 0 16px 34px -8px, rgba(55, 90, 60, 0.12) 0 6px 12px -4px",
  "--brand-title": "#233325",
  "--glass": "#D1EACE",
  "--glass-light": "#E5F5E1",
  "--glass-dark": "#183521",
  "--glass-reflex-dark": "1.18",
  "--glass-reflex-light": "0.88",
  "--glass-saturation": "154%",
  "--code-container-border": "#E5F5E1",
  "--code-container-bg": "#E5F5E1",
  "--code-container-fill-start": "54%",
  "--code-container-fill-mid": "23%",
  "--code-container-shine": "40%",
  "--code-container-top-reflex": "42%",
  "--code-container-border-start": "90%",
  "--code-container-border-end": "78%",
  "--code-container-overlay-opacity": "0.56",
} as const satisfies ThemeCssVariables;

const sourceShotFirewatchLightVariables = {
  "--text": "#7B1C2E",
  "--text-h": "#47202F",
  "--bg": "#DF7F52",
  "--bg-glow-warm": "#F3CE71",
  "--bg-glow-rose": "#D2534C",
  "--bg-glow-violet": "#A7263A",
  "--bg-glow-light": "#F1B960",
  "--bg-noise-opacity": "0.64",
  "--border": "#EDA458",
  "--code-bg": "#F3CE71",
  "--accent": "#53273B",
  "--accent-bg": "rgba(83, 39, 59, 0.1)",
  "--accent-border": "rgba(83, 39, 59, 0.44)",
  "--social-bg": "rgba(243, 206, 113, 0.56)",
  "--shadow": "rgba(71, 32, 47, 0.2) 0 16px 34px -8px, rgba(123, 28, 46, 0.14) 0 6px 12px -4px",
  "--brand-title": "#47202F",
  "--glass": "#F1B960",
  "--glass-light": "#F3CE71",
  "--glass-dark": "#47202F",
  "--glass-reflex-dark": "1.28",
  "--glass-reflex-light": "0.84",
  "--glass-saturation": "176%",
  "--code-container-border": "#F3CE71",
  "--code-container-bg": "#F3CE71",
  "--code-container-fill-start": "52%",
  "--code-container-fill-mid": "24%",
  "--code-container-shine": "38%",
  "--code-container-top-reflex": "40%",
  "--code-container-border-start": "88%",
  "--code-container-border-end": "76%",
  "--code-container-overlay-opacity": "0.58",
} as const satisfies ThemeCssVariables;

const sourceShotRoseQuartzVariables = {
  "--text": "#71324E",
  "--text-h": "#3F1D33",
  "--bg": "#F7DDE8",
  "--bg-glow-warm": "#FFF1B8",
  "--bg-glow-rose": "#F9A8D4",
  "--bg-glow-violet": "#A78BFA",
  "--bg-glow-light": "#D8B4FE",
  "--bg-noise-opacity": "0.48",
  "--border": "#F8C7DE",
  "--code-bg": "#FFF3F8",
  "--accent": "#7C3AED",
  "--accent-bg": "rgba(124, 58, 237, 0.1)",
  "--accent-border": "rgba(124, 58, 237, 0.44)",
  "--social-bg": "rgba(255, 243, 248, 0.58)",
  "--shadow": "rgba(63, 29, 51, 0.18) 0 16px 34px -8px, rgba(113, 50, 78, 0.1) 0 6px 12px -4px",
  "--brand-title": "#3F1D33",
  "--glass": "#FFEAF3",
  "--glass-light": "#FFFFFF",
  "--glass-dark": "#3F1D33",
  "--glass-reflex-dark": "1.2",
  "--glass-reflex-light": "0.86",
  "--glass-saturation": "168%",
  "--code-container-border": "#FFF3F8",
  "--code-container-bg": "#FFF3F8",
  "--code-container-fill-start": "54%",
  "--code-container-fill-mid": "23%",
  "--code-container-shine": "40%",
  "--code-container-top-reflex": "42%",
  "--code-container-border-start": "90%",
  "--code-container-border-end": "78%",
  "--code-container-overlay-opacity": "0.6",
} as const satisfies ThemeCssVariables;

const sourceShotTidepoolVariables = {
  "--text": "#245A62",
  "--text-h": "#123C48",
  "--bg": "#8FE3D9",
  "--bg-glow-warm": "#FFCF99",
  "--bg-glow-rose": "#E76F51",
  "--bg-glow-violet": "#4ECDC4",
  "--bg-glow-light": "#E7FFF8",
  "--bg-noise-opacity": "0.5",
  "--border": "#9CECE4",
  "--code-bg": "#E7FFF8",
  "--accent": "#E76F51",
  "--accent-bg": "rgba(231, 111, 81, 0.12)",
  "--accent-border": "rgba(231, 111, 81, 0.46)",
  "--social-bg": "rgba(231, 255, 248, 0.58)",
  "--shadow": "rgba(18, 60, 72, 0.18) 0 16px 34px -8px, rgba(36, 90, 98, 0.12) 0 6px 12px -4px",
  "--brand-title": "#123C48",
  "--glass": "#D9FFF8",
  "--glass-light": "#FFFFFF",
  "--glass-dark": "#123C48",
  "--glass-reflex-dark": "1.18",
  "--glass-reflex-light": "0.9",
  "--glass-saturation": "170%",
  "--code-container-border": "#E7FFF8",
  "--code-container-bg": "#E7FFF8",
  "--code-container-fill-start": "54%",
  "--code-container-fill-mid": "23%",
  "--code-container-shine": "40%",
  "--code-container-top-reflex": "42%",
  "--code-container-border-start": "90%",
  "--code-container-border-end": "80%",
  "--code-container-overlay-opacity": "0.58",
} as const satisfies ThemeCssVariables;

const sourceShotCinnamonSlateLightVariables = {
  "--text": "#7A6C5D",
  "--text-h": "#3B2F26",
  "--bg": "#E8D5C4",
  "--bg-glow-warm": "#D9A066",
  "--bg-glow-rose": "#C98656",
  "--bg-glow-violet": "#8A5A44",
  "--bg-glow-light": "#F4E4D2",
  "--bg-noise-opacity": "0.52",
  "--border": "#D6C3AE",
  "--code-bg": "#F6E9DA",
  "--accent": "#A8431F",
  "--accent-bg": "rgba(168, 67, 31, 0.1)",
  "--accent-border": "rgba(168, 67, 31, 0.44)",
  "--social-bg": "rgba(246, 233, 218, 0.6)",
  "--shadow": "rgba(59, 47, 38, 0.18) 0 16px 34px -8px, rgba(122, 108, 93, 0.12) 0 6px 12px -4px",
  "--brand-title": "#3B2F26",
  "--glass": "#F0DECB",
  "--glass-light": "#FFFFFF",
  "--glass-dark": "#3B2F26",
  "--glass-reflex-dark": "1.2",
  "--glass-reflex-light": "0.86",
  "--glass-saturation": "150%",
  "--code-container-border": "#F6E9DA",
  "--code-container-bg": "#F6E9DA",
  "--code-container-fill-start": "54%",
  "--code-container-fill-mid": "23%",
  "--code-container-shine": "40%",
  "--code-container-top-reflex": "42%",
  "--code-container-border-start": "90%",
  "--code-container-border-end": "78%",
  "--code-container-overlay-opacity": "0.58",
} as const satisfies ThemeCssVariables;

const sourceShotCinnamonSlateDarkVariables = {
  "--text": "#A8B0BC",
  "--text-h": "#EFEDE9",
  "--bg": "#241F1A",
  "--bg-glow-warm": "#8A4F2D",
  "--bg-glow-rose": "#6E3A24",
  "--bg-glow-violet": "#3A2E3F",
  "--bg-glow-light": "#C98656",
  "--bg-noise-opacity": "0.46",
  "--border": "#3A322B",
  "--code-bg": "#1E1915",
  "--accent": "#E0A875",
  "--accent-bg": "rgba(224, 168, 117, 0.14)",
  "--accent-border": "rgba(224, 168, 117, 0.48)",
  "--social-bg": "rgba(30, 25, 21, 0.6)",
  "--shadow": "rgba(0, 0, 0, 0.56) 0 18px 42px -10px, rgba(36, 31, 26, 0.42) 0 8px 18px -6px",
  "--brand-title": "#EFEDE9",
  "--glass": "#43362C",
  "--glass-light": "#EFEDE9",
  "--glass-dark": "#15110E",
  "--glass-reflex-dark": "2.05",
  "--glass-reflex-light": "0.36",
  "--glass-saturation": "150%",
  "--code-container-border": "#3A322B",
  "--code-container-bg": "#1E1915",
  "--code-container-fill-start": "44%",
  "--code-container-fill-mid": "17%",
  "--code-container-shine": "20%",
  "--code-container-top-reflex": "28%",
  "--code-container-border-start": "54%",
  "--code-container-border-end": "44%",
  "--code-container-overlay-opacity": "0.46",
} as const satisfies ThemeCssVariables;

const sourceShotCatppuccinLatteVariables = {
  "--text": "#6C6F85",
  "--text-h": "#4C4F69",
  "--bg": "#EFF1F5",
  "--bg-glow-warm": "#DF8E1D",
  "--bg-glow-rose": "#EA76CB",
  "--bg-glow-violet": "#8839EF",
  "--bg-glow-light": "#DC8A78",
  "--bg-noise-opacity": "0.44",
  "--border": "#CCD0DA",
  "--code-bg": "#E6E9EF",
  "--accent": "#8839EF",
  "--accent-bg": "rgba(136, 57, 239, 0.1)",
  "--accent-border": "rgba(136, 57, 239, 0.44)",
  "--social-bg": "rgba(230, 233, 239, 0.6)",
  "--shadow": "rgba(76, 79, 105, 0.16) 0 16px 34px -8px, rgba(108, 111, 133, 0.1) 0 6px 12px -4px",
  "--brand-title": "#4C4F69",
  "--glass": "#DCE0E8",
  "--glass-light": "#FFFFFF",
  "--glass-dark": "#4C4F69",
  "--glass-reflex-dark": "1.12",
  "--glass-reflex-light": "0.9",
  "--glass-saturation": "160%",
  "--code-container-border": "#E6E9EF",
  "--code-container-bg": "#E6E9EF",
  "--code-container-fill-start": "56%",
  "--code-container-fill-mid": "24%",
  "--code-container-shine": "44%",
  "--code-container-top-reflex": "46%",
  "--code-container-border-start": "92%",
  "--code-container-border-end": "82%",
  "--code-container-overlay-opacity": "0.6",
} as const satisfies ThemeCssVariables;

const sourceShotCatppuccinMacchiatoVariables = {
  "--text": "#A5ADCE",
  "--text-h": "#CAD3F5",
  "--bg": "#1E2030",
  "--bg-glow-warm": "#F5A97F",
  "--bg-glow-rose": "#ED8796",
  "--bg-glow-violet": "#C6A0F6",
  "--bg-glow-light": "#8BD5CA",
  "--bg-noise-opacity": "0.46",
  "--border": "#363A4F",
  "--code-bg": "#181926",
  "--accent": "#8BD5CA",
  "--accent-bg": "rgba(139, 213, 202, 0.14)",
  "--accent-border": "rgba(139, 213, 202, 0.48)",
  "--social-bg": "rgba(24, 25, 38, 0.6)",
  "--shadow": "rgba(0, 0, 0, 0.56) 0 18px 42px -10px, rgba(30, 32, 48, 0.42) 0 8px 18px -6px",
  "--brand-title": "#CAD3F5",
  "--glass": "#363A4F",
  "--glass-light": "#CAD3F5",
  "--glass-dark": "#0F1019",
  "--glass-reflex-dark": "2.05",
  "--glass-reflex-light": "0.34",
  "--glass-saturation": "170%",
  "--code-container-border": "#363A4F",
  "--code-container-bg": "#181926",
  "--code-container-fill-start": "44%",
  "--code-container-fill-mid": "17%",
  "--code-container-shine": "18%",
  "--code-container-top-reflex": "27%",
  "--code-container-border-start": "54%",
  "--code-container-border-end": "44%",
  "--code-container-overlay-opacity": "0.46",
} as const satisfies ThemeCssVariables;

const sourceShotDarculaVariables = {
  "--text": "#A9B7C6",
  "--text-h": "#DADFE5",
  "--bg": "#2B2B2B",
  "--bg-glow-warm": "#CC7832",
  "--bg-glow-rose": "#BC3F3C",
  "--bg-glow-violet": "#9876AA",
  "--bg-glow-light": "#A9B7C6",
  "--bg-noise-opacity": "0.46",
  "--border": "#3C3F41",
  "--code-bg": "#1E1E1E",
  "--accent": "#CC7832",
  "--accent-bg": "rgba(204, 120, 50, 0.14)",
  "--accent-border": "rgba(204, 120, 50, 0.48)",
  "--social-bg": "rgba(30, 30, 30, 0.6)",
  "--shadow": "rgba(0, 0, 0, 0.56) 0 18px 42px -10px, rgba(43, 43, 43, 0.42) 0 8px 18px -6px",
  "--brand-title": "#DADFE5",
  "--glass": "#3C3F41",
  "--glass-light": "#DADFE5",
  "--glass-dark": "#0A0A0A",
  "--glass-reflex-dark": "2",
  "--glass-reflex-light": "0.34",
  "--glass-saturation": "150%",
  "--code-container-border": "#3C3F41",
  "--code-container-bg": "#1E1E1E",
  "--code-container-fill-start": "44%",
  "--code-container-fill-mid": "17%",
  "--code-container-shine": "18%",
  "--code-container-top-reflex": "27%",
  "--code-container-border-start": "54%",
  "--code-container-border-end": "44%",
  "--code-container-overlay-opacity": "0.46",
} as const satisfies ThemeCssVariables;

function createMonoCodeTheme({
  background,
  displayName,
  foreground,
  muted,
  name,
  soft,
  type,
}: {
  background: string;
  displayName: string;
  foreground: string;
  muted: string;
  name: string;
  soft: string;
  type: "light" | "dark";
}) {
  return {
    name,
    displayName,
    type,
    fg: foreground,
    bg: background,
    settings: [
      {
        settings: {
          foreground,
          background,
        },
      },
      {
        scope: ["comment", "punctuation.definition.comment"],
        settings: {
          foreground: muted,
          fontStyle: "italic",
        },
      },
      {
        scope: [
          "constant",
          "entity.name.function",
          "entity.name.tag",
          "entity.other.attribute-name",
          "keyword",
          "storage",
          "support",
        ],
        settings: {
          foreground,
          fontStyle: "bold",
        },
      },
      {
        scope: ["punctuation", "string", "variable"],
        settings: {
          foreground: soft,
        },
      },
    ],
  } satisfies ThemeRegistration;
}

function createPaletteCodeTheme({
  accent,
  background,
  comment,
  displayName,
  foreground,
  functionName,
  keyword,
  name,
  number,
  property,
  string,
  type,
}: {
  accent: string;
  background: string;
  comment: string;
  displayName: string;
  foreground: string;
  functionName: string;
  keyword: string;
  name: string;
  number: string;
  property: string;
  string: string;
  type: "light" | "dark";
}) {
  return {
    name,
    displayName,
    type,
    fg: foreground,
    bg: background,
    settings: [
      {
        settings: {
          foreground,
          background,
        },
      },
      {
        scope: ["comment", "punctuation.definition.comment"],
        settings: {
          foreground: comment,
          fontStyle: "italic",
        },
      },
      {
        scope: ["keyword", "storage", "support.type", "entity.name.tag"],
        settings: {
          foreground: keyword,
          fontStyle: "bold",
        },
      },
      {
        scope: ["entity.name.function", "support.function", "meta.function-call"],
        settings: {
          foreground: functionName,
          fontStyle: "bold",
        },
      },
      {
        scope: ["string", "constant.character", "markup.inline.raw"],
        settings: {
          foreground: string,
        },
      },
      {
        scope: ["constant", "constant.numeric", "constant.language", "support.constant"],
        settings: {
          foreground: number,
        },
      },
      {
        scope: ["entity.other.attribute-name", "variable.other.property", "variable.parameter"],
        settings: {
          foreground: property,
        },
      },
      {
        scope: ["punctuation", "meta.brace", "meta.delimiter"],
        settings: {
          foreground: comment,
        },
      },
      {
        scope: ["variable", "identifier"],
        settings: {
          foreground: accent,
        },
      },
    ],
  } satisfies ThemeRegistration;
}

export const customCodeThemes = {
  "sourceshot-phoenix": createPaletteCodeTheme({
    name: "sourceshot-phoenix",
    displayName: "Phoenix Light",
    type: "light",
    foreground: sourceShotLightVariables["--text-h"],
    background: sourceShotLightVariables["--code-bg"],
    comment: sourceShotLightVariables["--text"],
    keyword: sourceShotLightVariables["--accent"],
    functionName: sourceShotLightVariables["--bg-glow-rose"],
    string: sourceShotLightVariables["--bg-glow-violet"],
    number: sourceShotLightVariables["--bg"],
    property: sourceShotLightVariables["--bg-glow-rose"],
    accent: sourceShotLightVariables["--text-h"],
  }),
  "sourceshot-phoenix-dark": createPaletteCodeTheme({
    name: "sourceshot-phoenix-dark",
    displayName: "Phoenix Dark",
    type: "dark",
    foreground: sourceShotDarkVariables["--text-h"],
    background: sourceShotDarkVariables["--code-bg"],
    comment: sourceShotDarkVariables["--text"],
    keyword: sourceShotDarkVariables["--accent"],
    functionName: "#e58d68",
    string: "#d88bb8",
    number: "#9ee3d6",
    property: "#c8b6ff",
    accent: sourceShotDarkVariables["--text-h"],
  }),
  "sourceshot-mono": createMonoCodeTheme({
    name: "sourceshot-mono",
    displayName: "Mono Light",
    type: "light",
    foreground: sourceShotMonoVariables["--text-h"],
    background: sourceShotMonoVariables["--bg"],
    muted: sourceShotMonoVariables["--bg-glow-violet"],
    soft: sourceShotMonoVariables["--text"],
  }),
  "sourceshot-mono-dark": createMonoCodeTheme({
    name: "sourceshot-mono-dark",
    displayName: "Mono Dark",
    type: "dark",
    foreground: sourceShotMonoDarkVariables["--text-h"],
    background: sourceShotMonoDarkVariables["--bg"],
    muted: sourceShotMonoDarkVariables["--bg-glow-light"],
    soft: sourceShotMonoDarkVariables["--text"],
  }),
  "sourceshot-aqua": createMonoCodeTheme({
    name: "sourceshot-aqua",
    displayName: "Aqua Light",
    type: "light",
    foreground: sourceShotAquaLightVariables["--text-h"],
    background: sourceShotAquaLightVariables["--code-bg"],
    muted: sourceShotAquaLightVariables["--bg-glow-violet"],
    soft: sourceShotAquaLightVariables["--text"],
  }),
  "sourceshot-aqua-dark": createMonoCodeTheme({
    name: "sourceshot-aqua-dark",
    displayName: "Aqua Dark",
    type: "dark",
    foreground: sourceShotAquaDarkVariables["--text-h"],
    background: sourceShotAquaDarkVariables["--code-bg"],
    muted: "#54B5DC",
    soft: sourceShotAquaDarkVariables["--text"],
  }),
  "sourceshot-lotus": createMonoCodeTheme({
    name: "sourceshot-lotus",
    displayName: "Lotus",
    type: "light",
    foreground: sourceShotLotusLightVariables["--text-h"],
    background: sourceShotLotusLightVariables["--code-bg"],
    muted: sourceShotLotusLightVariables["--bg-glow-violet"],
    soft: sourceShotLotusLightVariables["--text"],
  }),
  "sourceshot-firewatch": createMonoCodeTheme({
    name: "sourceshot-firewatch",
    displayName: "Summer",
    type: "light",
    foreground: sourceShotFirewatchLightVariables["--text-h"],
    background: sourceShotFirewatchLightVariables["--code-bg"],
    muted: sourceShotFirewatchLightVariables["--bg-glow-violet"],
    soft: sourceShotFirewatchLightVariables["--text"],
  }),
  "sourceshot-cinnamon-slate": createPaletteCodeTheme({
    name: "sourceshot-cinnamon-slate",
    displayName: "Cinnamon Slate Light",
    type: "light",
    foreground: sourceShotCinnamonSlateLightVariables["--text-h"],
    background: sourceShotCinnamonSlateLightVariables["--code-bg"],
    comment: sourceShotCinnamonSlateLightVariables["--text"],
    keyword: sourceShotCinnamonSlateLightVariables["--accent"],
    functionName: sourceShotCinnamonSlateLightVariables["--bg-glow-warm"],
    string: sourceShotCinnamonSlateLightVariables["--bg-glow-violet"],
    number: sourceShotCinnamonSlateLightVariables["--bg-glow-rose"],
    property: "#8A4A2A",
    accent: sourceShotCinnamonSlateLightVariables["--text-h"],
  }),
  "sourceshot-cinnamon-slate-dark": createPaletteCodeTheme({
    name: "sourceshot-cinnamon-slate-dark",
    displayName: "Cinnamon Slate Dark",
    type: "dark",
    foreground: sourceShotCinnamonSlateDarkVariables["--text-h"],
    background: sourceShotCinnamonSlateDarkVariables["--code-bg"],
    comment: sourceShotCinnamonSlateDarkVariables["--text"],
    keyword: sourceShotCinnamonSlateDarkVariables["--accent"],
    functionName: sourceShotCinnamonSlateDarkVariables["--bg-glow-warm"],
    string: "#D4A373",
    number: "#E0A875",
    property: "#C98656",
    accent: sourceShotCinnamonSlateDarkVariables["--text-h"],
  }),
  "sourceshot-catppuccin-latte": createPaletteCodeTheme({
    name: "sourceshot-catppuccin-latte",
    displayName: "Catppuccin Latte",
    type: "light",
    foreground: sourceShotCatppuccinLatteVariables["--text-h"],
    background: sourceShotCatppuccinLatteVariables["--code-bg"],
    comment: sourceShotCatppuccinLatteVariables["--text"],
    keyword: sourceShotCatppuccinLatteVariables["--bg-glow-violet"],
    functionName: sourceShotCatppuccinLatteVariables["--bg-glow-rose"],
    string: sourceShotCatppuccinLatteVariables["--bg-glow-warm"],
    number: "#FE640B",
    property: "#DF8E1D",
    accent: sourceShotCatppuccinLatteVariables["--text-h"],
  }),
  "sourceshot-catppuccin-macchiato": createPaletteCodeTheme({
    name: "sourceshot-catppuccin-macchiato",
    displayName: "Catppuccin Macchiato",
    type: "dark",
    foreground: sourceShotCatppuccinMacchiatoVariables["--text-h"],
    background: sourceShotCatppuccinMacchiatoVariables["--code-bg"],
    comment: sourceShotCatppuccinMacchiatoVariables["--text"],
    keyword: sourceShotCatppuccinMacchiatoVariables["--bg-glow-violet"],
    functionName: sourceShotCatppuccinMacchiatoVariables["--bg-glow-rose"],
    string: sourceShotCatppuccinMacchiatoVariables["--bg-glow-warm"],
    number: "#F5A97F",
    property: sourceShotCatppuccinMacchiatoVariables["--bg-glow-light"],
    accent: sourceShotCatppuccinMacchiatoVariables["--text-h"],
  }),
  "sourceshot-darcula": createPaletteCodeTheme({
    name: "sourceshot-darcula",
    displayName: "Darcula",
    type: "dark",
    foreground: sourceShotDarculaVariables["--text-h"],
    background: sourceShotDarculaVariables["--code-bg"],
    comment: sourceShotDarculaVariables["--text"],
    keyword: sourceShotDarculaVariables["--accent"],
    functionName: "#FFC66D",
    string: "#6A8759",
    number: "#6897BB",
    property: "#9876AA",
    accent: sourceShotDarculaVariables["--text-h"],
  }),
  "sourceshot-rose-quartz": createPaletteCodeTheme({
    name: "sourceshot-rose-quartz",
    displayName: "Rose Quartz",
    type: "light",
    foreground: sourceShotRoseQuartzVariables["--text-h"],
    background: sourceShotRoseQuartzVariables["--code-bg"],
    comment: sourceShotRoseQuartzVariables["--text"],
    keyword: sourceShotRoseQuartzVariables["--accent"],
    functionName: "#BE185D",
    string: "#6D28D9",
    number: "#B45309",
    property: "#DB2777",
    accent: sourceShotRoseQuartzVariables["--text-h"],
  }),
  "sourceshot-tidepool": createPaletteCodeTheme({
    name: "sourceshot-tidepool",
    displayName: "Tidepool",
    type: "light",
    foreground: sourceShotTidepoolVariables["--text-h"],
    background: sourceShotTidepoolVariables["--code-bg"],
    comment: sourceShotTidepoolVariables["--text"],
    keyword: sourceShotTidepoolVariables["--accent"],
    functionName: "#0F766E",
    string: "#0E7490",
    number: "#C2410C",
    property: "#2563EB",
    accent: sourceShotTidepoolVariables["--text-h"],
  }),
} as const satisfies Record<string, ThemeRegistration>;

export const appThemeDefinitions = [
  {
    label: "Phoenix Light",
    value: "light",
    codeTheme: "sourceshot-phoenix",
    colorScheme: "light",
    variables: sourceShotLightVariables,
  },
  {
    label: "Phoenix Dark",
    value: "dark",
    codeTheme: "sourceshot-phoenix-dark",
    colorScheme: "dark",
    variables: sourceShotDarkVariables,
  },
  {
    label: "Mono",
    value: "mono",
    codeTheme: "sourceshot-mono",
    colorScheme: "light",
    variables: sourceShotMonoVariables,
  },
  {
    label: "Mono Dark",
    value: "mono-dark",
    codeTheme: "sourceshot-mono-dark",
    colorScheme: "dark",
    variables: sourceShotMonoDarkVariables,
  },
  {
    label: "Aqua Light",
    value: "aqua-light",
    codeTheme: "sourceshot-aqua",
    colorScheme: "light",
    variables: sourceShotAquaLightVariables,
  },
  {
    label: "Aqua Dark",
    value: "aqua-dark",
    codeTheme: "sourceshot-aqua-dark",
    colorScheme: "dark",
    variables: sourceShotAquaDarkVariables,
  },
  {
    label: "Lotus",
    value: "lotus-light",
    codeTheme: "sourceshot-lotus",
    colorScheme: "light",
    variables: sourceShotLotusLightVariables,
  },
  {
    label: "Summer",
    value: "firewatch-light",
    codeTheme: "sourceshot-firewatch",
    colorScheme: "light",
    variables: sourceShotFirewatchLightVariables,
  },
  {
    label: "Cinnamon Slate Light",
    value: "cinnamon-slate-light",
    codeTheme: "sourceshot-cinnamon-slate",
    colorScheme: "light",
    variables: sourceShotCinnamonSlateLightVariables,
  },
  {
    label: "Cinnamon Slate Dark",
    value: "cinnamon-slate-dark",
    codeTheme: "sourceshot-cinnamon-slate-dark",
    colorScheme: "dark",
    variables: sourceShotCinnamonSlateDarkVariables,
  },
  {
    label: "Catppuccin Latte",
    value: "catppuccin-latte",
    codeTheme: "sourceshot-catppuccin-latte",
    colorScheme: "light",
    variables: sourceShotCatppuccinLatteVariables,
  },
  {
    label: "Catppuccin Macchiato",
    value: "catppuccin-macchiato",
    codeTheme: "sourceshot-catppuccin-macchiato",
    colorScheme: "dark",
    variables: sourceShotCatppuccinMacchiatoVariables,
  },
  {
    label: "Darcula",
    value: "darcula",
    codeTheme: "sourceshot-darcula",
    colorScheme: "dark",
    variables: sourceShotDarculaVariables,
  },
  {
    label: "Rose Quartz",
    value: "rose-quartz",
    codeTheme: "sourceshot-rose-quartz",
    colorScheme: "light",
    variables: sourceShotRoseQuartzVariables,
  },
  {
    label: "Tidepool",
    value: "tidepool",
    codeTheme: "sourceshot-tidepool",
    colorScheme: "light",
    variables: sourceShotTidepoolVariables,
  },
] as const;

export type AppThemeDefinition = (typeof appThemeDefinitions)[number];
export type AppThemeValue = AppThemeDefinition["value"];
export type CodeThemeName = AppThemeDefinition["codeTheme"];

export const themeCssVariableNames = Object.keys(
  sourceShotLightVariables,
) as readonly ThemeCssVariableName[];

export function getThemeDefinition(theme: AppThemeValue) {
  return (
    appThemeDefinitions.find((themeDefinition) => themeDefinition.value === theme) ??
    appThemeDefinitions[0]
  );
}
