import type { ThemeRegistration } from "shiki/core";

const sourceShotLightVariables = {
  "--text": "#6b6375",
  "--text-h": "#08060d",
  "--bg": "#e07a5f",
  "--bg-glow-warm": "#f2b06f",
  "--bg-glow-rose": "#cf536d",
  "--bg-glow-violet": "#6f3e98",
  "--bg-glow-light": "#f3dfc7",
  "--bg-noise-opacity": "1",
  "--border": "#e5e4e7",
  "--code-bg": "#f4f3ec",
  "--accent": "#aa3bff",
  "--accent-bg": "rgba(170, 59, 255, 0.1)",
  "--accent-border": "rgba(170, 59, 255, 0.5)",
  "--social-bg": "rgba(244, 243, 236, 0.5)",
  "--shadow": "rgba(0, 0, 0, 0.1) 0 10px 15px -3px, rgba(0, 0, 0, 0.05) 0 4px 6px -2px",
  "--brand-title": "#000000",
  "--glass": "#ececf0",
  "--glass-light": "#ffffff",
  "--glass-dark": "#000000",
  "--glass-reflex-dark": "1",
  "--glass-reflex-light": "1",
  "--glass-saturation": "150%",
  "--code-container-border": "#ffffff",
  "--code-container-bg": "#fbf4ee",
  "--code-container-fill-start": "56%",
  "--code-container-fill-mid": "22%",
  "--code-container-shine": "46%",
  "--code-container-top-reflex": "46%",
  "--code-container-border-start": "96%",
  "--code-container-border-end": "100%",
  "--code-container-overlay-opacity": "0.82",
} as const;

type ThemeCssVariableName = keyof typeof sourceShotLightVariables;
export type ThemeCssVariables = Readonly<Record<ThemeCssVariableName, string>>;

const sourceShotDarkVariables = {
  "--text": "#a9b1bd",
  "--text-h": "#f6f2eb",
  "--bg": "#111116",
  "--bg-glow-warm": "#a44e39",
  "--bg-glow-rose": "#65324c",
  "--bg-glow-violet": "#302756",
  "--bg-glow-light": "#1e4c52",
  "--bg-noise-opacity": "0.72",
  "--border": "#2b2d35",
  "--code-bg": "#171820",
  "--accent": "#77dac8",
  "--accent-bg": "rgba(119, 218, 200, 0.14)",
  "--accent-border": "rgba(119, 218, 200, 0.48)",
  "--social-bg": "rgba(30, 33, 42, 0.52)",
  "--shadow": "rgba(0, 0, 0, 0.46) 0 16px 34px -8px, rgba(0, 0, 0, 0.32) 0 6px 12px -4px",
  "--brand-title": "#fff6ec",
  "--glass": "#4a5360",
  "--glass-light": "#ffffff",
  "--glass-dark": "#000000",
  "--glass-reflex-dark": "2.1",
  "--glass-reflex-light": "0.36",
  "--glass-saturation": "176%",
  "--code-container-border": "#2e3340",
  "--code-container-bg": "#11151e",
  "--code-container-fill-start": "48%",
  "--code-container-fill-mid": "18%",
  "--code-container-shine": "22%",
  "--code-container-top-reflex": "28%",
  "--code-container-border-start": "54%",
  "--code-container-border-end": "58%",
  "--code-container-overlay-opacity": "0.42",
} as const satisfies ThemeCssVariables;

const sourceShotMonoVariables = {
  "--text": "#4f554f",
  "--text-h": "#222323",
  "--bg": "#f0f6f0",
  "--bg-glow-warm": "#f8fff8",
  "--bg-glow-rose": "#dbe2db",
  "--bg-glow-violet": "#626862",
  "--bg-glow-light": "#ffffff",
  "--bg-noise-opacity": "0.44",
  "--border": "#cdd6cd",
  "--code-bg": "#eef4ee",
  "--accent": "#222323",
  "--accent-bg": "rgba(34, 35, 35, 0.08)",
  "--accent-border": "rgba(34, 35, 35, 0.46)",
  "--social-bg": "rgba(240, 246, 240, 0.58)",
  "--shadow": "rgba(34, 35, 35, 0.16) 0 14px 28px -8px, rgba(34, 35, 35, 0.08) 0 6px 12px -4px",
  "--brand-title": "#222323",
  "--glass": "#f0f6f0",
  "--glass-light": "#ffffff",
  "--glass-dark": "#222323",
  "--glass-reflex-dark": "1.18",
  "--glass-reflex-light": "0.82",
  "--glass-saturation": "0%",
  "--code-container-border": "#f0f6f0",
  "--code-container-bg": "#edf3ed",
  "--code-container-fill-start": "50%",
  "--code-container-fill-mid": "18%",
  "--code-container-shine": "34%",
  "--code-container-top-reflex": "40%",
  "--code-container-border-start": "84%",
  "--code-container-border-end": "70%",
  "--code-container-overlay-opacity": "0.5",
} as const satisfies ThemeCssVariables;

const sourceShotMonoDarkVariables = {
  "--text": "#d7ded7",
  "--text-h": "#f0f6f0",
  "--bg": "#222323",
  "--bg-glow-warm": "#f0f6f0",
  "--bg-glow-rose": "#3d403d",
  "--bg-glow-violet": "#111212",
  "--bg-glow-light": "#697069",
  "--bg-noise-opacity": "0.36",
  "--border": "#444944",
  "--code-bg": "#1f2020",
  "--accent": "#f0f6f0",
  "--accent-bg": "rgba(240, 246, 240, 0.1)",
  "--accent-border": "rgba(240, 246, 240, 0.48)",
  "--social-bg": "rgba(34, 35, 35, 0.58)",
  "--shadow": "rgba(0, 0, 0, 0.52) 0 16px 34px -8px, rgba(0, 0, 0, 0.34) 0 6px 12px -4px",
  "--brand-title": "#f7fff7",
  "--glass": "#3d403d",
  "--glass-light": "#f0f6f0",
  "--glass-dark": "#000000",
  "--glass-reflex-dark": "1.9",
  "--glass-reflex-light": "0.34",
  "--glass-saturation": "0%",
  "--code-container-border": "#3d403d",
  "--code-container-bg": "#222323",
  "--code-container-fill-start": "42%",
  "--code-container-fill-mid": "16%",
  "--code-container-shine": "18%",
  "--code-container-top-reflex": "28%",
  "--code-container-border-start": "58%",
  "--code-container-border-end": "44%",
  "--code-container-overlay-opacity": "0.48",
} as const satisfies ThemeCssVariables;

const sourceShotAquaLightVariables = {
  "--text": "#224DA2",
  "--text-h": "#191C4F",
  "--bg": "#58B9DE",
  "--bg-glow-warm": "#A9E1F2",
  "--bg-glow-rose": "#BFE9F5",
  "--bg-glow-violet": "#3B7FC2",
  "--bg-glow-light": "#D2EFF8",
  "--bg-noise-opacity": "0.58",
  "--border": "#A9E1F2",
  "--code-bg": "#D2EFF8",
  "--accent": "#0B1376",
  "--accent-bg": "rgba(11, 19, 118, 0.1)",
  "--accent-border": "rgba(11, 19, 118, 0.42)",
  "--social-bg": "rgba(210, 239, 248, 0.58)",
  "--shadow": "rgba(11, 19, 118, 0.18) 0 16px 34px -8px, rgba(34, 77, 162, 0.12) 0 6px 12px -4px",
  "--brand-title": "#191C4F",
  "--glass": "#BFE9F5",
  "--glass-light": "#D2EFF8",
  "--glass-dark": "#0B1376",
  "--glass-reflex-dark": "1.24",
  "--glass-reflex-light": "0.92",
  "--glass-saturation": "168%",
  "--code-container-border": "#D2EFF8",
  "--code-container-bg": "#D2EFF8",
  "--code-container-fill-start": "54%",
  "--code-container-fill-mid": "24%",
  "--code-container-shine": "42%",
  "--code-container-top-reflex": "44%",
  "--code-container-border-start": "92%",
  "--code-container-border-end": "82%",
  "--code-container-overlay-opacity": "0.58",
} as const satisfies ThemeCssVariables;

const sourceShotAquaDarkVariables = {
  "--text": "#BEE8F4",
  "--text-h": "#D1ECF4",
  "--bg": "#020440",
  "--bg-glow-warm": "#1D49A0",
  "--bg-glow-rose": "#3578BD",
  "--bg-glow-violet": "#070F72",
  "--bg-glow-light": "#54B5DC",
  "--bg-noise-opacity": "0.5",
  "--border": "#1D49A0",
  "--code-bg": "#070F72",
  "--accent": "#78CAE7",
  "--accent-bg": "rgba(120, 202, 231, 0.14)",
  "--accent-border": "rgba(120, 202, 231, 0.5)",
  "--social-bg": "rgba(7, 15, 114, 0.56)",
  "--shadow": "rgba(0, 0, 0, 0.56) 0 18px 42px -10px, rgba(2, 4, 64, 0.4) 0 8px 18px -6px",
  "--brand-title": "#D1ECF4",
  "--glass": "#1D49A0",
  "--glass-light": "#D1ECF4",
  "--glass-dark": "#020440",
  "--glass-reflex-dark": "2.2",
  "--glass-reflex-light": "0.38",
  "--glass-saturation": "186%",
  "--code-container-border": "#1D49A0",
  "--code-container-bg": "#070F72",
  "--code-container-fill-start": "46%",
  "--code-container-fill-mid": "19%",
  "--code-container-shine": "20%",
  "--code-container-top-reflex": "30%",
  "--code-container-border-start": "58%",
  "--code-container-border-end": "48%",
  "--code-container-overlay-opacity": "0.46",
} as const satisfies ThemeCssVariables;

const sourceShotLotusLightVariables = {
  "--text": "#375A3C",
  "--text-h": "#233325",
  "--bg": "#A3D1A5",
  "--bg-glow-warm": "#BADDBA",
  "--bg-glow-rose": "#D1EACE",
  "--bg-glow-violet": "#6FA977",
  "--bg-glow-light": "#E5F5E1",
  "--bg-noise-opacity": "0.52",
  "--border": "#BADDBA",
  "--code-bg": "#E5F5E1",
  "--accent": "#183521",
  "--accent-bg": "rgba(24, 53, 33, 0.1)",
  "--accent-border": "rgba(24, 53, 33, 0.42)",
  "--social-bg": "rgba(229, 245, 225, 0.6)",
  "--shadow": "rgba(24, 53, 33, 0.18) 0 16px 34px -8px, rgba(55, 90, 60, 0.12) 0 6px 12px -4px",
  "--brand-title": "#233325",
  "--glass": "#D1EACE",
  "--glass-light": "#E5F5E1",
  "--glass-dark": "#183521",
  "--glass-reflex-dark": "1.18",
  "--glass-reflex-light": "0.88",
  "--glass-saturation": "154%",
  "--code-container-border": "#E5F5E1",
  "--code-container-bg": "#E5F5E1",
  "--code-container-fill-start": "54%",
  "--code-container-fill-mid": "23%",
  "--code-container-shine": "40%",
  "--code-container-top-reflex": "42%",
  "--code-container-border-start": "90%",
  "--code-container-border-end": "78%",
  "--code-container-overlay-opacity": "0.56",
} as const satisfies ThemeCssVariables;

const sourceShotLotusDarkVariables = {
  "--text": "#CEE8CB",
  "--text-h": "#D9E9D3",
  "--bg": "#081A0F",
  "--bg-glow-warm": "#325538",
  "--bg-glow-rose": "#4D8155",
  "--bg-glow-violet": "#13301D",
  "--bg-glow-light": "#6AA673",
  "--bg-noise-opacity": "0.46",
  "--border": "#325538",
  "--code-bg": "#13301D",
  "--accent": "#86C38E",
  "--accent-bg": "rgba(134, 195, 142, 0.14)",
  "--accent-border": "rgba(134, 195, 142, 0.5)",
  "--social-bg": "rgba(19, 48, 29, 0.58)",
  "--shadow": "rgba(0, 0, 0, 0.54) 0 18px 42px -10px, rgba(8, 26, 15, 0.42) 0 8px 18px -6px",
  "--brand-title": "#D9E9D3",
  "--glass": "#325538",
  "--glass-light": "#D9E9D3",
  "--glass-dark": "#081A0F",
  "--glass-reflex-dark": "2",
  "--glass-reflex-light": "0.36",
  "--glass-saturation": "164%",
  "--code-container-border": "#325538",
  "--code-container-bg": "#13301D",
  "--code-container-fill-start": "46%",
  "--code-container-fill-mid": "18%",
  "--code-container-shine": "19%",
  "--code-container-top-reflex": "28%",
  "--code-container-border-start": "56%",
  "--code-container-border-end": "46%",
  "--code-container-overlay-opacity": "0.46",
} as const satisfies ThemeCssVariables;

const sourceShotFirewatchLightVariables = {
  "--text": "#7B1C2E",
  "--text-h": "#47202F",
  "--bg": "#DF7F52",
  "--bg-glow-warm": "#F3CE71",
  "--bg-glow-rose": "#D2534C",
  "--bg-glow-violet": "#A7263A",
  "--bg-glow-light": "#F1B960",
  "--bg-noise-opacity": "0.64",
  "--border": "#EDA458",
  "--code-bg": "#F3CE71",
  "--accent": "#53273B",
  "--accent-bg": "rgba(83, 39, 59, 0.1)",
  "--accent-border": "rgba(83, 39, 59, 0.44)",
  "--social-bg": "rgba(243, 206, 113, 0.56)",
  "--shadow": "rgba(71, 32, 47, 0.2) 0 16px 34px -8px, rgba(123, 28, 46, 0.14) 0 6px 12px -4px",
  "--brand-title": "#47202F",
  "--glass": "#F1B960",
  "--glass-light": "#F3CE71",
  "--glass-dark": "#47202F",
  "--glass-reflex-dark": "1.28",
  "--glass-reflex-light": "0.84",
  "--glass-saturation": "176%",
  "--code-container-border": "#F3CE71",
  "--code-container-bg": "#F3CE71",
  "--code-container-fill-start": "52%",
  "--code-container-fill-mid": "24%",
  "--code-container-shine": "38%",
  "--code-container-top-reflex": "40%",
  "--code-container-border-start": "88%",
  "--code-container-border-end": "76%",
  "--code-container-overlay-opacity": "0.58",
} as const satisfies ThemeCssVariables;

const sourceShotFirewatchDarkVariables = {
  "--text": "#EEB55C",
  "--text-h": "#E0B95B",
  "--bg": "#30061B",
  "--bg-glow-warm": "#DB7B4D",
  "--bg-glow-rose": "#761729",
  "--bg-glow-violet": "#440D25",
  "--bg-glow-light": "#CE4E48",
  "--bg-noise-opacity": "0.52",
  "--border": "#761729",
  "--code-bg": "#440D25",
  "--accent": "#E99F53",
  "--accent-bg": "rgba(233, 159, 83, 0.14)",
  "--accent-border": "rgba(233, 159, 83, 0.5)",
  "--social-bg": "rgba(68, 13, 37, 0.58)",
  "--shadow": "rgba(0, 0, 0, 0.58) 0 18px 42px -10px, rgba(48, 6, 27, 0.44) 0 8px 18px -6px",
  "--brand-title": "#E0B95B",
  "--glass": "#761729",
  "--glass-light": "#E0B95B",
  "--glass-dark": "#30061B",
  "--glass-reflex-dark": "2.15",
  "--glass-reflex-light": "0.34",
  "--glass-saturation": "190%",
  "--code-container-border": "#761729",
  "--code-container-bg": "#440D25",
  "--code-container-fill-start": "46%",
  "--code-container-fill-mid": "18%",
  "--code-container-shine": "18%",
  "--code-container-top-reflex": "27%",
  "--code-container-border-start": "54%",
  "--code-container-border-end": "44%",
  "--code-container-overlay-opacity": "0.48",
} as const satisfies ThemeCssVariables;

function createMonoCodeTheme({
  background,
  displayName,
  foreground,
  muted,
  name,
  soft,
  type,
}: {
  background: string;
  displayName: string;
  foreground: string;
  muted: string;
  name: string;
  soft: string;
  type: "light" | "dark";
}) {
  return {
    name,
    displayName,
    type,
    fg: foreground,
    bg: background,
    settings: [
      {
        settings: {
          foreground,
          background,
        },
      },
      {
        scope: ["comment", "punctuation.definition.comment"],
        settings: {
          foreground: muted,
          fontStyle: "italic",
        },
      },
      {
        scope: [
          "constant",
          "entity.name.function",
          "entity.name.tag",
          "entity.other.attribute-name",
          "keyword",
          "storage",
          "support",
        ],
        settings: {
          foreground,
          fontStyle: "bold",
        },
      },
      {
        scope: ["punctuation", "string", "variable"],
        settings: {
          foreground: soft,
        },
      },
    ],
  } satisfies ThemeRegistration;
}

export const customCodeThemes = {
  "sourceshot-mono": createMonoCodeTheme({
    name: "sourceshot-mono",
    displayName: "Mono Light",
    type: "light",
    foreground: sourceShotMonoVariables["--text-h"],
    background: sourceShotMonoVariables["--bg"],
    muted: sourceShotMonoVariables["--bg-glow-violet"],
    soft: sourceShotMonoVariables["--text"],
  }),
  "sourceshot-mono-dark": createMonoCodeTheme({
    name: "sourceshot-mono-dark",
    displayName: "Mono Dark",
    type: "dark",
    foreground: sourceShotMonoDarkVariables["--text-h"],
    background: sourceShotMonoDarkVariables["--bg"],
    muted: sourceShotMonoDarkVariables["--bg-glow-light"],
    soft: sourceShotMonoDarkVariables["--text"],
  }),
  "sourceshot-aqua": createMonoCodeTheme({
    name: "sourceshot-aqua",
    displayName: "Aqua Light",
    type: "light",
    foreground: sourceShotAquaLightVariables["--text-h"],
    background: sourceShotAquaLightVariables["--code-bg"],
    muted: sourceShotAquaLightVariables["--bg-glow-violet"],
    soft: sourceShotAquaLightVariables["--text"],
  }),
  "sourceshot-aqua-dark": createMonoCodeTheme({
    name: "sourceshot-aqua-dark",
    displayName: "Aqua Dark",
    type: "dark",
    foreground: sourceShotAquaDarkVariables["--text-h"],
    background: sourceShotAquaDarkVariables["--code-bg"],
    muted: sourceShotAquaDarkVariables["--bg-glow-light"],
    soft: sourceShotAquaDarkVariables["--text"],
  }),
  "sourceshot-lotus": createMonoCodeTheme({
    name: "sourceshot-lotus",
    displayName: "Lotus Light",
    type: "light",
    foreground: sourceShotLotusLightVariables["--text-h"],
    background: sourceShotLotusLightVariables["--code-bg"],
    muted: sourceShotLotusLightVariables["--bg-glow-violet"],
    soft: sourceShotLotusLightVariables["--text"],
  }),
  "sourceshot-lotus-dark": createMonoCodeTheme({
    name: "sourceshot-lotus-dark",
    displayName: "Lotus Dark",
    type: "dark",
    foreground: sourceShotLotusDarkVariables["--text-h"],
    background: sourceShotLotusDarkVariables["--code-bg"],
    muted: sourceShotLotusDarkVariables["--bg-glow-light"],
    soft: sourceShotLotusDarkVariables["--text"],
  }),
  "sourceshot-firewatch": createMonoCodeTheme({
    name: "sourceshot-firewatch",
    displayName: "Firewatch Light",
    type: "light",
    foreground: sourceShotFirewatchLightVariables["--text-h"],
    background: sourceShotFirewatchLightVariables["--code-bg"],
    muted: sourceShotFirewatchLightVariables["--bg-glow-violet"],
    soft: sourceShotFirewatchLightVariables["--text"],
  }),
  "sourceshot-firewatch-dark": createMonoCodeTheme({
    name: "sourceshot-firewatch-dark",
    displayName: "Firewatch Dark",
    type: "dark",
    foreground: sourceShotFirewatchDarkVariables["--text-h"],
    background: sourceShotFirewatchDarkVariables["--code-bg"],
    muted: sourceShotFirewatchDarkVariables["--bg-glow-light"],
    soft: sourceShotFirewatchDarkVariables["--text"],
  }),
} as const satisfies Record<string, ThemeRegistration>;

export const appThemeDefinitions = [
  {
    label: "Light",
    value: "light",
    codeTheme: "vitesse-light",
    colorScheme: "light",
    variables: sourceShotLightVariables,
  },
  {
    label: "Dark",
    value: "dark",
    codeTheme: "vitesse-dark",
    colorScheme: "dark",
    variables: sourceShotDarkVariables,
  },
  {
    label: "Mono",
    value: "mono",
    codeTheme: "sourceshot-mono",
    colorScheme: "light",
    variables: sourceShotMonoVariables,
  },
  {
    label: "Mono Dark",
    value: "mono-dark",
    codeTheme: "sourceshot-mono-dark",
    colorScheme: "dark",
    variables: sourceShotMonoDarkVariables,
  },
  {
    label: "Aqua Light",
    value: "aqua-light",
    codeTheme: "sourceshot-aqua",
    colorScheme: "light",
    variables: sourceShotAquaLightVariables,
  },
  {
    label: "Aqua Dark",
    value: "aqua-dark",
    codeTheme: "sourceshot-aqua-dark",
    colorScheme: "dark",
    variables: sourceShotAquaDarkVariables,
  },
  {
    label: "Lotus Light",
    value: "lotus-light",
    codeTheme: "sourceshot-lotus",
    colorScheme: "light",
    variables: sourceShotLotusLightVariables,
  },
  {
    label: "Lotus Dark",
    value: "lotus-dark",
    codeTheme: "sourceshot-lotus-dark",
    colorScheme: "dark",
    variables: sourceShotLotusDarkVariables,
  },
  {
    label: "Firewatch Light",
    value: "firewatch-light",
    codeTheme: "sourceshot-firewatch",
    colorScheme: "light",
    variables: sourceShotFirewatchLightVariables,
  },
  {
    label: "Firewatch Dark",
    value: "firewatch-dark",
    codeTheme: "sourceshot-firewatch-dark",
    colorScheme: "dark",
    variables: sourceShotFirewatchDarkVariables,
  },
] as const;

export type AppThemeDefinition = (typeof appThemeDefinitions)[number];
export type AppThemeValue = AppThemeDefinition["value"];
export type CodeThemeName = AppThemeDefinition["codeTheme"];

export const themeCssVariableNames = Object.keys(
  sourceShotLightVariables,
) as readonly ThemeCssVariableName[];

export function getThemeDefinition(theme: AppThemeValue) {
  return (
    appThemeDefinitions.find((themeDefinition) => themeDefinition.value === theme) ??
    appThemeDefinitions[0]
  );
}
